Add GitHub Actions workflow to publish files to production
mozilla/legal-docs pull request #1719
Opened 2022-03-23 21:41 UTC by pmac

This will add a workflow action that will take a comma separated list of
files as input (or "ALL" by default if all files are desired) and create
a pull-request for updating the content of the files and all of the
translations thereof. After reviewing the PR it can be merged to publish
all of the file changes to the production website.

2022-03-23 21:43 UTC, pmac commented
If this works I'll update the README to reflect the updated production push procedure.

2022-03-24 07:00 UTC, flodolo requested changes
A few fixes needed, but this seems to work great.

2022-03-24 20:55 UTC, pmac commented
Thanks for the review! I'll fix it up.

2022-03-24 20:56 UTC, pmac commented on .github/scripts/copy_files.py
> +    for fp in file_paths:
Good idea. Should probably exit with a non-zero exit code as well.

2022-03-24 20:56 UTC, pmac commented on .github/workflows/prod_push.yml
> +          TMP_DIR=$(mktemp)
Ah. I was getting too fancy :) Thanks.

2022-03-24 21:37 UTC, pmac commented
Updates are done. Thanks again for taking a look and for the excellent suggestion flod! After this merges I'll file a PR to update the README instructions and send an email about it.

2022-03-25 05:55 UTC, flodolo approved these changes
Did some [more testing](https://github.com/flodolo/legal-docs/actions/workflows/prod_push.yml) on my fork, and it works great!

For documentation: one of the side effects of the approach you used for the search, is that you can use wildcards in the input field (e.g. `mdn*`). Not sure if that was planned, but it's very handy.

2022-03-25 13:20 UTC, pmac commented
> For documentation: one of the side effects of the approach you used for the search is that you can use wildcards in the input field (e.g. `mdn*`). Not sure if that was planned, but it's very handy.

It wasn't exactly intended, but it's a good point. I'll include that in the documentation.

2022-03-25 13:33 UTC, merged