General Update for product and service changes
mozilla/legal-docs pull request #1724
Opened 2022-03-30 21:45 UTC by mafeld

2022-03-30 22:29 UTC, peiying2 requested changes
@mafeld this looks good to me. One comment on how `Firefox Account` is referenced, it is now lower case `Firefox account` unless it's used as a tile/headline, but otherwise, it should be lower case. 

Even in UI, when you check your Firefox account in the Fx browser, it is lower case.

See the discussion on this: https://github.com/mozilla/fxa/issues/10654.  

Another one from the team: https://github.com/mozilla/fxa/issues/10693.

2022-03-31 05:34 UTC, flodolo commented on en/firefox_cloud_services_tos.md
> +    In order to use some of the Services, you'll need to create a Firefox Account.  During registration, you will be asked to set a password. You are responsible for keeping your password confidentia
Could we drop the double spaces after punctuation? They're not effective anyway when rendered, and they're used iconsistently.

2022-03-31 05:34 UTC, flodolo commented on en/firefox_cloud_services_tos.md
> +    (e) Firefox Sync lets you access information stored in Firefox across devices, including your tabs, awesome bar, passwords, bookmarks, and browser preferences. You can enable and disable Firefox
A few notes:
* We dropped the use of Sync with Proton, so it should be lowercase.
* We talk about Settings, not Tools (and this was unified with Proton)

2022-04-01 18:42 UTC, peiying2 approved these changes

2022-04-01 18:42 UTC, merged