Create Mozilla_Accounts_Privacy_Notice.md
mozilla/legal-docs pull request #1942
Opened 2023-10-13 18:10 UTC by jejohnsonmoz

New Accounts Notice to take account of change from Firefox Accounts > Mozilla Accounts (most of this language was previously in the Firefox Browser notice.

2023-10-13 19:02 UTC, peiying2 requested changes
Overall looks good.  Only a few comments.

2023-10-13 19:02 UTC, peiying2 commented on en/Mozilla_Accounts_Privacy_Notice.md
> +You can learn more about [managing your data](https://support.mozilla.org/en-US/kb/firefox-accounts-managing-account-data) and how to [enable or disable sync](https://support.mozilla.org/kb/how-do-i-
Remove `en-US` in the link.

2023-10-13 20:26 UTC, jejohnsonmoz commented on en/Mozilla_Accounts_Privacy_Notice.md
> +__Technical data.__ To display which devices are synced to your Mozilla account and for security functionality, we store your device operating system, browser and version, timestamp, locale, and the
Great question - I'm not sure! Can we change to "(such as Pocket or Monitor)?

2023-10-13 20:30 UTC, jejohnsonmoz commented on en/Mozilla_Accounts_Privacy_Notice.md
> +In this Privacy Notice, we explain what data Mozilla collects and shares about you. We also adhere to the practices outlined in the [Mozilla Privacy Policy](https://www.mozilla.org/privacy/) for how
I think I did this!

2023-10-13 20:30 UTC, jejohnsonmoz commented on en/Mozilla_Accounts_Privacy_Notice.md
> +- [Firefox Browser](https://www.mozilla.org/en-US/privacy/firefox/)
Think I did this too!

2023-10-13 20:30 UTC, jejohnsonmoz commented on en/Mozilla_Accounts_Privacy_Notice.md
> +__Technical data.__ To display which devices are synced to your Mozilla account and for security functionality, we store your device operating system, browser and version, timestamp, locale, and the
I amended to "Pocket or Mozilla VPN". Let me know if that doesn't make sense!

2023-10-13 20:31 UTC, jejohnsonmoz commented on en/Mozilla_Accounts_Privacy_Notice.md
> +You can learn more about [managing your data](https://support.mozilla.org/en-US/kb/firefox-accounts-managing-account-data) and how to [enable or disable sync](https://support.mozilla.org/kb/how-do-i-
Think I did this.

2023-10-16 17:46 UTC, peiying2 commented on en/Mozilla_Accounts_Privacy_Notice.md
> +{: datetime="2023-11-1" }
date format should be `{: datetime="2023-11-01" }` (01 instead of 1).

2023-10-16 17:46 UTC, peiying2 commented on en/Mozilla_Accounts_Privacy_Notice.md
> +
Remove extra line space

2023-10-16 17:47 UTC, peiying2 requested changes
@jejohnsonmoz a couple of more change request.

2023-10-16 19:38 UTC, mafeld commented
addressed the latest two comments from @peiying2

2023-10-16 19:41 UTC, peiying2 approved these changes

2023-10-16 19:41 UTC, merged