Update subscription_services_tos.md
mozilla/legal-docs pull request #1943
Opened 2023-10-13 19:11 UTC by mafeld

Change Firefox Accounts to Mozilla Accounts

2023-10-13 19:28 UTC, peiying2 approved these changes

2023-10-14 06:44 UTC, flodolo commented
Noticed while searching for account in the doc

> If we decide to suspend or end your access, we will try to notify you at the email address associated with your account or the next time you attempt to access your Account.

Should that last `Account` be lowercase?

2023-10-16 17:59 UTC, peiying2 requested changes
@mafeld one more fix and it's ready to go.

2023-10-16 19:01 UTC, peiying2 approved these changes

2023-10-16 19:01 UTC, merged

2023-10-16 19:02 UTC, mafeld commented
done