Update firefox_cloud_services_tos.md
mozilla/legal-docs pull request #1944
Opened 2023-10-13 19:44 UTC by mafeld

Update Firefox Accounts to Mozilla Accounts

2023-10-13 19:45 UTC, mafeld commented
In addition to the changes in the document, we should probably change the title of this doc. @pmac - Is there anything we need to prepare for Bedrock before changing the name of this doc to Mozilla_Accounts_tos?

2023-10-13 19:50 UTC, pmac commented
Yes there is actually. We load and show these docs based on the file name. I think the best way to do this is to publish this doc, then make a copy of it with the new name as well. Then we can make the code change for the site. Once that is deployed we can remove the old doc file name. Does that make sense?

The annoying thing is that we'll need to do that for all of the translations as well.

2023-10-13 20:07 UTC, mafeld commented
No problem. Let's get to Nov 1, and then we can worry about renaming as clean up afterwards.

2023-10-13 20:19 UTC, peiying2 requested changes
The updates look good. However, there are still plenty mentions of Firefox account and Firefox Monitor throughout the document. Please have another go.

2023-10-13 20:19 UTC, peiying2 commented on en/firefox_cloud_services_tos.md
>      (b) Firefox Relay allows you to keep your primary email address safe and private from online services by making unique, alias email addresses that allow you to send and receive emails without rev
Firefox account

2023-10-13 20:21 UTC, mafeld commented on en/firefox_cloud_services_tos.md
>      (b) Firefox Relay allows you to keep your primary email address safe and private from online services by making unique, alias email addresses that allow you to send and receive emails without rev
Ok. I think I caught the rest

2023-10-16 18:04 UTC, peiying2 commented on en/firefox_cloud_services_tos.md
> +    (c) Firefox Monitor is an informational service to promote online security by informing you of public data breaches. You can scan email addresses on our website to see most publicly known breache
Firefox Monitor -> Mozilla Monitor

2023-10-16 18:04 UTC, peiying2 commented on en/firefox_cloud_services_tos.md
>      It is your responsibility to protect your online accounts using strong and different passwords, security questions, two-factor authentication, password managers, and other safety measures. Althou
Firefox Monitor -> Mozilla Monitor

2023-10-16 18:07 UTC, peiying2 requested changes
@mafeld need to change to Mozilla Monitor.

2023-10-16 18:57 UTC, mafeld commented
The Mozilla Monitor renaming is happening at a different time, so we are leaving it as Firefox Monitor for this revision.

2023-10-16 18:58 UTC, peiying2 approved these changes

2023-10-16 18:59 UTC, merged