Update mdn_plus_terms.md
mozilla/legal-docs pull request #1945
Opened 2023-10-13 19:53 UTC by mafeld

Firefox accounts -> Mozilla accounts

2023-10-13 19:59 UTC, peiying2 approved these changes

2023-10-16 18:22 UTC, peiying2 requested changes
@mafeld should be lower case `a` in Mozilla account(s) except for headings. Please go over the entire doc.

2023-10-16 18:55 UTC, mafeld commented
Thank you. I have fixed the lowercase a

2023-10-16 18:56 UTC, peiying2 approved these changes

2023-10-16 18:57 UTC, merged