Update hubs_privacy_notice.md
mozilla/legal-docs pull request #1948
Opened 2023-10-13 20:46 UTC by jejohnsonmoz

Updating to account for Firefox > Mozilla Accounts, and to add standard wording re: personal data requests at the end. 

Also updated to change name from Twitter > X

2023-10-13 21:06 UTC, peiying2 requested changes
Minor change request.

2023-10-13 21:06 UTC, peiying2 commented on en/hubs_privacy_notice.md
>  __Usage Information.__ We receive information about the rooms and users in your Hubs instance. For instance, we learn when you create and delete rooms, how many rooms are in your Hubs instance, and h
Lower case `i` as in `Usage information.`

2023-10-13 21:06 UTC, peiying2 commented on en/hubs_privacy_notice.md
> +You can learn more about [managing your Mozilla Account data](https://support.mozilla.org/kb/firefox-accounts-managing-account-data). Also, much of the information that we store about our Mozilla acc
Lower case `a` as in Mozilla account`

2023-10-14 06:51 UTC, flodolo commented on en/hubs_privacy_notice.md
> +{: datetime="2023-11-1" }
```suggestion
{: datetime="2023-11-01" }
```

2023-10-16 18:51 UTC, peiying2 approved these changes

2023-10-16 18:51 UTC, merged