Update firefox_privacy_notice.md
mozilla/legal-docs pull request #1983
Opened 2023-12-22 16:27 UTC by jejohnsonmoz

Minor edits relating to Google Play requirements, opting out of Accuweather suggestions and clarifying marketing campaign data sharing.

2023-12-22 16:57 UTC, peiying2 requested changes
One minor change request.

2023-12-22 16:57 UTC, peiying2 commented on en/firefox_privacy_notice.md
> +In the US, Mozilla may also receive keyword location search data (such as when you search for “Boston”) and share this with our partners to provide recommended and sponsored content. Where this occur
remove `en-US` in the link

2024-01-03 18:11 UTC, jejohnsonmoz commented
Hi @Francesco Lodolo ***@***.***> - thanks for checking, re: the
verbiage, the language is a little choppy but it makes sense to us and we'd
like to proceed as is.

I'll go in now and make the other changes re: the /en/ and the missing
space and wrong dash etc...

On Wed, Dec 27, 2023 at 8:12 AM Francesco Lodolo ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In en/firefox_privacy_notice.md
> <https://github.com/mozilla/legal-docs/pull/1983#discussion_r1435223970>:
>
> > @@ -35,7 +35,9 @@ Mozilla generally receives royalties when you use one of the default or optional
>
>  __Firefox Suggest__ uses data to help deliver better information with less effort. By default, Firefox Suggest shows you recommended and sponsored content based on local data stored on your own computer, such as websites from your browsing history, bookmarks and open tabs (which is not sent to Mozilla). Firefox Suggest does send to Mozilla:
>
> -* __Location data__: Firefox temporarily sends Mozilla your IP address, which we use to suggest content based on your country, state, and city. Mozilla may share location information with our [partners](https://support.mozilla.org/kb/firefox-suggest#w_who-are-mozillas-partners), but partners will not receive your IP address. In the US, Mozilla may also receive keyword location search data (such as when you search for “Boston”) and share this with our partners to provide recommended and sponsored content. Where this occurs, neither Mozilla nor our partners are able to associate the keyword search with an individual user once the search suggestion has been served.
> +* __Location data__: Firefox temporarily sends Mozilla your IP address, which we use to suggest content based on your country, state, and city. Mozilla may share location information with our [partners](https://support.mozilla.org/kb/firefox-suggest#w_who-are-mozillas-partners), but partners will not receive your IP address.
> +
> +In the US, Mozilla may also receive keyword location search data (such as when you search for “Boston”) and share this with our partners to provide recommended and sponsored content. Where this occurs, neither Mozilla nor our partners are able to associate the keyword search with an individual user once the search suggestion has been served.You can remove this functionality at any time by turning off sponsored suggestions - more information on how to do this is available in the relevant [Firefox Support](https://support.mozilla.org/en-US/kb/firefox-suggest?as=u&utm_source=inproduct) page.
>
> ⬇️ Suggested change
>
> -In the US, Mozilla may also receive keyword location search data (such as when you search for “Boston”) and share this with our partners to provide recommended and sponsored content. Where this occurs, neither Mozilla nor our partners are able to associate the keyword search with an individual user once the search suggestion has been served.You can remove this functionality at any time by turning off sponsored suggestions - more information on how to do this is available in the relevant [Firefox Support](https://support.mozilla.org/en-US/kb/firefox-suggest?as=u&utm_source=inproduct) page.
> +In the US, Mozilla may also receive keyword location search data (such as when you search for “Boston”) and share this with our partners to provide recommended and sponsored content. Where this occurs, neither Mozilla nor our partners are able to associate the keyword search with an individual user once the search suggestion has been served. You can remove this functionality at any time by turning off sponsored suggestions — more information on how to do this is available in the relevant [Firefox Support](https://support.mozilla.org/kb/firefox-suggest?as=u&utm_source=inproduct) page.
>
> Missing space, wrong dash.
> ------------------------------
>
> In en/firefox_privacy_notice.md
> <https://github.com/mozilla/legal-docs/pull/1983#discussion_r1435224391>:
>
> > @@ -92,7 +94,9 @@ Read the full documentation [here](https://firefox-source-docs.mozilla.org/toolk
>  __Campaign and referral data__: This helps Mozilla understand the effectiveness of our marketing campaigns.
>  {: #referraltracking }
>
> -Firefox by default sends Mozilla HTTP data that may be included with Firefox’s installer. This enables us to determine the website domain or advertising campaign (if any) that referred you to our download page. Read the [documentation](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/environment.html#attribution) or [opt out](https://support.mozilla.org/kb/desktop-attribution-privacy) before installation. Firefox by default also sends marketing campaign data to Adjust, our analytics vendor, which has its own [privacy policy](https://www.adjust.com/terms/privacy-policy/). Campaign data includes a Google advertising ID or Android ID, IP address, timestamp, country, language/locale, operating system, and app version. Read the [documentation](https://dictionary.telemetry.mozilla.org/apps/fenix?itemType=metrics&page=1&search=adjust).
> +Firefox by default sends Mozilla HTTP data that may be included with Firefox’s installer. This enables us to determine the website domain or advertising campaign (if any) that referred you to our download page. Read the [documentation](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/environment.html#attribution) or [opt out](https://support.mozilla.org/kb/desktop-attribution-privacy) before installation.
> +
> +Firefox by default also shares de-identified marketing campaign data to our campaign marketing vendors to measure and improve our marketing campaigns. This includes Adjust, which has its own [privacy policy](https://www.adjust.com/terms/privacy-policy/). It also includes Google. Campaign data includes a Google advertising ID or Android ID, IP address, timestamp, country, language/locale, operating system, and app version. Read the [documentation](https://dictionary.telemetry.mozilla.org/apps/fenix?itemType=metrics&page=1&search=adjust).
>
> It also includes Google. Campaign data includes a Google advertising ID …
>
> Is this correct? I feel like the first sentence should either not be
> there, or something else is missing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/legal-docs/pull/1983#pullrequestreview-1794745110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCQFSNFGWDBSU4RXTG3FBJTYLQNCXAVCNFSM6AAAAABBAAYOUKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJUG42DKMJRGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-03 18:18 UTC, flodolo commented
> verbiage, the language is a little choppy but it makes sense to us and we'd like to proceed as is.

I think the problem is that I was trying to connect `It also includes Google.` to the sentence after, not the one before. I get the meaning now.

On a practical note, we'll need the actual dates before sending this out for translation

2024-01-03 18:20 UTC, jejohnsonmoz commented
As in the actual date it will go live? January 17th...

On Wed, Jan 3, 2024 at 1:19 PM Francesco Lodolo ***@***.***>
wrote:

> verbiage, the language is a little choppy but it makes sense to us and
> we'd like to proceed as is.
>
> I think the problem is that I was trying to connect It also includes
> Google. to the sentence after, not the one before. I get the meaning now.
>
> On a practical note, we'll need the actual dates before sending this out
> for translation
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/legal-docs/pull/1983#issuecomment-1875779722>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCQFSNBQ64TD4WLVASTCXNLYMWOJVAVCNFSM6AAAAABBAAYOUKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZVG43TSNZSGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-03 18:27 UTC, jejohnsonmoz commented
Sorry sorry, you can ignore that - I was confusing it with the Subscription
Services Notice which needs to go live Jan 17th. If you need a specific
date, happy to use Jan 17th (if that's feasible) so we update two notices
on the same day. Otherwise the date can just be whenever the translations
are ready.

On Wed, Jan 3, 2024 at 1:19 PM Jennifer Johnson ***@***.***>
wrote:

> As in the actual date it will go live? January 17th...
>
> On Wed, Jan 3, 2024 at 1:19 PM Francesco Lodolo ***@***.***>
> wrote:
>
>> verbiage, the language is a little choppy but it makes sense to us and
>> we'd like to proceed as is.
>>
>> I think the problem is that I was trying to connect It also includes
>> Google. to the sentence after, not the one before. I get the meaning now.
>>
>> On a practical note, we'll need the actual dates before sending this out
>> for translation
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mozilla/legal-docs/pull/1983#issuecomment-1875779722>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BCQFSNBQ64TD4WLVASTCXNLYMWOJVAVCNFSM6AAAAABBAAYOUKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZVG43TSNZSGI>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-01-03 18:38 UTC, flodolo commented
What I mean is that we currently have a placeholder instead of a validity date in this update:

```
*Effective [insert data once known*
{: datetime="2023-[update once known]" }
```

This needs to be fixed before we ask the vendor to translate the content, because dates need to be localized.

Once the content is ready and reviewed, you will need to request translation via Jira (I think you have made requests for Mozilla accounts in the past, the process is the same).

2024-01-03 18:54 UTC, jejohnsonmoz reviewed
Date updated

2024-01-03 18:55 UTC, flodolo approved these changes

2024-01-03 20:07 UTC, jejohnsonmoz commented
Jira ticket here: https://mozilla-hub.atlassian.net/browse/L10NV-165

2024-01-03 22:25 UTC, peiying2 approved these changes

2024-01-03 22:26 UTC, merged