Create AMO Legal landing page
mozilla/legal-docs pull request #2022
Opened 2024-03-18 22:38 UTC by aroybalreid

Landing page to indicate which policies govern AMO content.

2024-03-19 04:25 UTC, peiying2 commented on en/AMO Legal landing page
> +[addons.mozilla.org (AMO)](https://addons.mozilla.org/) is an online community that hosts content created by Firefox users and developers.  By participating in this community, you agree to comply wit
Remove `en-US` in both links

2024-03-19 04:27 UTC, peiying2 commented on en/AMO Legal landing page
> +You can choose to contribute extensions, ratings, themes, collections, or other content for other members of the community to use.  You can also upload or otherwise add content to create a user profi
Remove en-US in the link

2024-03-19 04:28 UTC, peiying2 commented on en/AMO Legal landing page
> +For extensions, themes, collections, and user profiles: Visit the listing page and click the “Report” button
Insert a line break before listed items.

2024-03-19 04:28 UTC, peiying2 commented on en/AMO Legal landing page
> +
Remove extra line break.

2024-03-19 04:31 UTC, peiying2 requested changes
A few general formatting issues

2024-03-20 17:29 UTC, peiying2 approved these changes

2024-03-21 05:54 UTC, flodolo approved these changes

2024-03-21 05:54 UTC, merged