Create Formulaic Privacy Notice
mozilla/legal-docs pull request #2023
Opened 2024-03-18 23:39 UTC by aroybalreid

Privacy Notice for Formulaic product

We can host this on this page https://www.mozilla.org/en-US/privacy/.  We will also want a URL that the Formulaic Product team can link to

2024-03-19 04:36 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +This privacy notice explains what information Formulaic collects, shares, and processes, and why. We also adhere to the [Mozilla Privacy Policy](https://www.mozilla.org/privacy/) when we receive, han
Insert a line space

2024-03-19 04:40 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +**Technical data.** We receive basic telemetry data by default, which we use to improve the performance, stability, and security of the Service, including information about your device, including har
Insert a line break

2024-03-19 04:40 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +**Username.** This is a unique, public-facing account name chosen by you. Any content that you choose to publish on the Formulaic website or otherwise contribute to the Service will include this user
Insert a line break

2024-03-19 04:56 UTC, peiying2 requested changes
Did not mark up all the formatting related issues. 
- Line break between heading and first paragraph
- Link break before listed or bullet items.
- URL: remove `en` or `en-US` in links

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +-Sign in with Google, which places a cookie on your device to assist with sign-in and authentication to the Service. When you sign into the Service, you accept the associated [Privacy Policy](https:/
- Line break before the listed items.
- Remove en-US in the URL: `https://policies.google.com/privacy`

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +-Google Analytics to obtain metrics on how users engage with our websites. This helps us to improve site content. For more information about how Google uses your personal information, please visit [G
Can we remove `en` in the link to automatically redirect to default language of choice?

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +**Account data.** You need a Google Account in order to create an account and access the Service. When you log in with your Google Account to access the Service, we receive your name, email address,
Insert a line break before bullet items.

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +We use third parties to provide the Service to you, and have contracted with these companies requiring them to protect your information (Third-Party Services):
Line break between heading and paragraph

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +**Google Cloud Provider.** Google Cloud Provider (GCP) is a cloud-computing platform. We use GCP to facilitate account creation, authenticate users, host content, and provide access to certain Third-
Line break before bullet items.

2024-03-19 04:56 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +The Service is not directed to children under 18 years of age, and we do not knowingly collect or solicit personal information from children. If the Service unknowingly collects personal information
Insert line break between heading and first paragraph.

2024-03-19 04:59 UTC, peiying2 commented on en/Formulaic Privacy Notice
> +This privacy notice applies to Formulaic, a service that allows users to query, create, share, and manage templates for querying artificial intelligence (AI) based large language models (LLMs) (the “
Use curly quotes (not straight quotes) as in `“Service”` for the other ones in this paragraph

2024-03-19 07:12 UTC, flodolo commented
File preview here: https://github.com/mozilla/legal-docs/blob/0cfbb4178da1f8b4580a956776174d1d79937bc9/en/formulaic_privacy_notice.md

2024-03-19 18:33 UTC, aroybalreid commented
I see some formatting issues.  Is there a way for me to edit at this point?  It is not clear that I can do so right now

2024-03-21 17:11 UTC, peiying2 approved these changes

2024-03-21 17:37 UTC, flodolo approved these changes

2024-03-21 17:37 UTC, merged